### ISSUE TITLE
Weak hash value for hash table

### ISSUE THREAD

**Issue by insuyun** [ChengyuSong/Kirenenko#4]
Hi, Chengyu.

I guess you have used xxhash [for making hash](https://github.com/ChengyuSong/Kirenenko/blob/master/llvm_mode/dfsan_rt/dfsan/dfsan.cc#L239).
But in your hash table, you are using [other hash, which seems very weak](https://github.com/ChengyuSong/Kirenenko/blob/master/llvm_mode/dfsan_rt/dfsan/union_hashtable.cc#L15).

Did you intentionally use the weak hash? or just forget to use the xxhash value?

**Comment by ChengyuSong** [comment]
The hash table is implemented before we started to use xxhash. I've updated the implementation.
